### ISSUE TITLE
Paste_id's are in order.

### ISSUE THREAD

**Issue by menonmoon** [jordansamuel/PASTE#102]
I figure this is a bug since no competent developer would have this as a feature.

**Comment by spawniectes** [comment]
Anyone has solved this issue?

**Comment by robertfels** [comment]
@spawniectes I changed the "id" field in my database to varchar and used on the "INSERT"-Statement a php uniqid() function, to generate a short textual id.
It was quiet easy.

**Comment by jordansamuel** [comment]
not a bug
