### ISSUE TITLE
"Database connection failed" when trying to install

### ISSUE THREAD

**Issue by HarunaFujiwara** [jordansamuel/PASTE#108]
hi!
I got the problem stating "Database connection failed" when trying to install
i tried creating the config.php file manually and through the install.php none works, any ideas?

**Comment by HarunaFujiwara** [comment]
solved

**Comment by psycholyzern** [comment]
Mind to close issue?

**Comment by Duguayster** [comment]
How were you able solve it @HarunaFujiwara ? I'm running into the same issue

**Comment by HarunaFujiwara** [comment]
hey man, i dont have my site anymore but as far as i remember it was
because i just installed it wrong or because i set up my server wrong


Am Sa., 26. Okt. 2019 um 18:38 Uhr schrieb Pole_Ice <
notifications@github.com>:
