### ISSUE TITLE
Unable to install 2.2

### ISSUE THREAD

**Issue by mzch** [jordansamuel/PASTE#117]
I tried to install 2.2, but not completed. Please see below:

![Shot003](https://user-images.githubusercontent.com/621178/74079427-b157ac80-4a7a-11ea-80a0-2f0cdd3cac76.png)

<img width="553" alt="ScreenShot 2020-02-08 13 56 25" src="https://user-images.githubusercontent.com/621178/74079439-e237e180-4a7a-11ea-848f-abadda1025f1.png">

**Comment by jordansamuel** [comment]
please disable any extensions you have, worker-content-script.js and fsUtils.js isn't part of Paste.

**Comment by mzch** [comment]
I cloned this repository freshly and don't add any extensions.

**Comment by mzch** [comment]
And any browsers got 500 error on `https://pastemoe.com/install/configure.php`

**Comment by mzch** [comment]
I can set up manually and configure from admin panel, but this issue haven't been fixed.

**Comment by jordansamuel** [comment]
You have "PW" displaying in the User and Password field, this is not default behaviour of paste. Your browser appears to be trying to do something. The errors are coming from javascript files not included with paste, please check which browser extensions you have loaded in chrome://extensions

**Comment by mzch** [comment]
I tried Vivaldi without any extensions, but got the same result...

**Comment by jordansamuel** [comment]
Extensions loaded in Chrome are also loaded in Vivaldi by default as they
are cross compatible.

**Comment by mzch** [comment]
I confirmed no extension on `vivaldi://extensions`...?

**Comment by jordansamuel** [comment]
this issue should be fixed for you in https://github.com/jordansamuel/PASTE/commit/77cb470fa39e8229e9c0dfe7abe2cf93b94716c9

**Comment by mzch** [comment]
Great! Thanks for your effort.
