### ISSUE TITLE
Unable to install PASTE 2.2

### ISSUE THREAD

**Issue by jameswill** [jordansamuel/PASTE#120]
Hi,

I was trying to install PASTE 2.2 on one of my test servers and was unable to do so as I am getting following error.

mysqli_connect(): (28000/1045): Access denied for user 'root'@'localhost' (using password: NO) in [PATH]/[TO]/[PASTE2.2]/install/install.php on line 24
Failed to connect:Access denied for user 'root'@'localhost' (using password: NO)

On further debugging I found that install/configure.php contains syntax error at line number 81

It should be

// Secret key for paste encryption
" . '$sec_key' . " = '$data_sec';
define('SECRET',md5(" . '$sec_key));

instead of 

// Secret key for paste encryption
$sec_key' . " = '$data_sec';
define('SECRET',md5(" . '$sec_key));

which is why it is unable to generate config.php and hence not getting its database details to propagate data.

If this is true, please make the required correction.

**Comment by jordansamuel** [comment]
thanks for bringing to my attention,
fixed in [77cb470fa39e8229e9c0dfe7abe2cf93b94716c9](https://github.com/jordansamuel/PASTE/commit/77cb470fa39e8229e9c0dfe7abe2cf93b94716c9)
