### ISSUE TITLE
Uncaught TypeError in paste 2.2

### ISSUE THREAD

**Issue by Kashouryo** [jordansamuel/PASTE#126]
Fatal error: Uncaught TypeError: Argument 1 passed to mysqli_fetch_array() must be an instance of mysqli_result, bool given in /.../PASTE/admin/dashboard.php:59\nStack trace:\n#0 /.../PASTE/admin/dashboard.php(59): mysqli_fetch_array()\n#1 {main}

I am using HHVM 3.21.0 but I don't think that's the issue here.

**Comment by Kashouryo** [comment]
confirmed, HHVM is the issue...

**Comment by techinnov-974** [comment]
Hello I use wamp 3.2.2.2 I have the same concern
