### ISSUE TITLE
Cant change hoempage

### ISSUE THREAD

**Issue by asimo10** [jordansamuel/PASTE#129]
I want to add google analytics but I can't find the HTML file. please help me

**Comment by BasToTheMax** [comment]
The index.php is the index page

Or you can look in the theme folder

**Comment by BasToTheMax** [comment]
> I want to add google analytics but I can't find the HTML file. please help me

In the admin dashboard you can add a Google analytics tag

**Comment by asimo10** [comment]
thanks
