### ISSUE TITLE
Timeout settings ?

### ISSUE THREAD

**Issue by didli** [jordansamuel/PASTE#140]
First, thank you for Paste. It's growing on me as I use it as a notepad / snippet manager of sorts, and it's a nice, simple and clean app for that. 
So thank you !
Now for the question : I'm searching for the file/settings that controls how long a user remain connected. Right now I would prefer to avoid this timeout but I suppose it was configure that way for security concerns ?
I would also like to know if this app is still under development and if there's a roadmap for it (future features) ?
Anyway, thank you again for Paste.

**Comment by jordansamuel** [comment]
Do you mean timeout settings when signed in? Paste doesn't use cookies at the moment, so that is controlled by your php session settings in php.ini
