### ISSUE TITLE
[Bug] Unable to login to admin dashboard

### ISSUE THREAD

**Issue by RHQ-Rusty** [jordansamuel/PASTE#146]
Upon completing _**multiply**_ fresh installs of Paste, the suite works wonderfully. Registering for user accounts, posting pastes, etc. all work, but I _cannot_ log into the Admin account. #62 seems to hint that the Admin is already logged in - how do I log it out / log back into it / use it to access Dashboard?

Thanks!

### Installation
- Paste version: 2.2

**Comment by jordansamuel** [comment]
that's strange, I've never come across that before I'll have to look into
it. As paste doesn't use cookies your session should self destruct when you
close or refresh your browser. Can you show me what settings you're using
in php.ini for php session values?

**Comment by RHQ-Rusty** [comment]
> that's strange, I've never come across that before I'll have to look into it. As paste doesn't use cookies your session should self destruct when you close or refresh your browser. Can you show me what settings you're using in php.ini for php session values?

Thanks for the speedy reply, sorry for mine being so late! I was using extremely generous values just to make sure it wasn't my PHP.ini. I'm talking 1G Memory, 512 Max Upload, etc. and Session Times of 120+ seconds. For some reason it just wasn't letting me in to the Admin Dashboard :(

**Comment by thinkverse** [comment]
@RHQ-Rusty have this issue persisted or did you find a solution for it? I think I've narrowed down the issue, do you have more than one admin account perhaps? It seems I can reproduce the issue when I have more than one admin account. If you can, try limiting your admin accounts to one and see if you can log in then. 🙂

**Comment by thinkverse** [comment]
This issue should now be resolved with 3f02873, will not be available in a stable release until later, but if you're comfortable with development builds you can always fork directly from the master branch.
