### ISSUE TITLE
No Unique ID for Pastes! paste.php?id=4

### ISSUE THREAD

**Issue by jumbubly** [jordansamuel/PASTE#148]
are you on discord bro? any way to contact you... is there any way to change this to the unique links like from pastebin.com?

**Comment by jordansamuel** [comment]
Not without editing the script, but it is a feature request and will be in
the next version. I am available on IRC: irc.collectiveirc.net in #Paste

**Comment by kat953162** [comment]
Excited for this feature. I was searching through the closed issues specifically to see if anyone mentioned it.

Thanks for the heads up.

**Comment by jordansamuel** [comment]
I will do my best to release a new version shortly, keep an eye out. There
are alot of updates in this one release.

**Comment by Godofh3ell** [comment]
> 

Can U please give an update? When can we expect this feature?

**Comment by godgutten** [comment]
Any news?
