### ISSUE TITLE
Uncaught Error: Call to undefined function mb_strlen() in /var/www/html/code/index.php:251 Stack trace: #0

### ISSUE THREAD

**Issue by imwireless** [jordansamuel/PASTE#153]
When a user submits a paste they get the error
Fatal error: Uncaught Error: Call to undefined function mb_strlen() in /var/www/html/code/index.php:251 Stack trace: #0 {main} thrown in /var/www/html/code/index.php on line 251

How do I repair this?

**Comment by imwireless** [comment]
I removed that line from the index.php and resolved my issue.

**Comment by jordansamuel** [comment]
please install Multibyte String (php mod mbstring)
