### ISSUE TITLE
Is the width of the sidebar modifiable?

### ISSUE THREAD

**Issue by PassionFlix** [jordansamuel/PASTE#154]
hello is it possible to modify the number of characters or the width of the sidebar so as not to have the [...]?
![Screenshot_20210223-161100_Chrome.jpg](https://user-images.githubusercontent.com/71842302/108864074-23e9ea80-75f2-11eb-9739-ae0a8c5568f7.jpg)

**Comment by jordansamuel** [comment]
not really without screwing up the way the sidebar is displayed as more
characters would be detrimental to that, not keeping within overflow. But
if you wish, you can change in sidebar.php
