### ISSUE TITLE
PHP Warning:  mysqli_fetch_array() expects parameter 1 to be mysqli_result, bool given in /home/subdomain/index.php on line 184

### ISSUE THREAD

**Issue by Zxce3** [jordansamuel/PASTE#157]
PHP Warning:  mysqli_fetch_array() expects parameter 1 to be mysqli_result, bool given in /home/subdomain/index.php on line 184

I got 403 
Forbidden

Access to this resource on the server is denied!

**Comment by thinkverse** [comment]
> PHP Warning: mysqli_fetch_array() expects parameter 1 to be mysqli_result, bool given in /home/subdomain/index.php on line 184

The issue has been resolved in development, will be in the next release. 👍

As for the 403 that has to do with how your server is configured and not PASTE itself, make sure your server is configured correctly and has all its correct permissions.
