### ISSUE TITLE
[Bug] Undefined variable warning in `functions.php`

### ISSUE THREAD

**Issue by bunder2015** [jordansamuel/PASTE#163]
I ran into some problems testing PASTE on a new install... (php 7.4.19)

`Undefined variable: sec_key in includes/functions.php on line 37`

I tried copying `$sec_key` from `config.php` to `includes/functions.php` (because including it wasn't working) and got a different error...

`openssl_encrypt(): Using an empty Initialization Vector (iv) is potentially insecure and not recommended in includes/functions.php on line 30`

From what I can tell, `openssl_encrypt` is supposed to take 4 (or 5) arguments, and we're only giving it 3.

**Comment by thinkverse** [comment]
This issue is reproducible and has been added to [known issues](https://github.com/jordansamuel/PASTE/projects/4). 👍
