### ISSUE TITLE
[Bug] Missing import causes `sitemap.php` to throw an error.

### ISSUE THREAD

**Issue by bunder2015** [jordansamuel/PASTE#165]
I ran into some problems testing PASTE on a new install... (php 7.4.19)

`Call to undefined function paste_protocol() in admin/sitemap.php:206\nStack trace:\n#0 {main}\n  thrown in admin/sitemap.php on line 206`

Placing a `require_once('../includes/functions.php');` anywhere in admin/sitemap.php fixes this up.

I also moved `paste_protocol()` to above `addToSitemap()` in includes/functions.php.

**Comment by thinkverse** [comment]
Can reproduce this issue, will checkout the linked PR. 👍
