### ISSUE TITLE
[Bug] XSS vulnerability found when adding paste

### ISSUE THREAD

**Issue by secghost** [jordansamuel/PASTE#180]
![Screenshot_49](https://user-images.githubusercontent.com/61977913/132613068-9c587e4e-f731-4618-a1b7-098757ae78be.png)

i try with this payload xss and get a xss , can you fix about this

payload : **</teXtarEa/</scRipt/--!>\x3csVg/<sVg/oNloAd=alert(document.cookie)//>\x3e**

**Comment by thinkverse** [comment]
Thank you for reporting, I will try and get a fix out as soon as I have the time. 👍

**Comment by thinkverse** [comment]
Pushed a quick fix (fed78541) for the issue. I suggest downloading directly from the repository since the next major release is still a ways away.

**Comment by secghost** [comment]
thanks for fixed,i love it this paste:"
