### ISSUE TITLE
Right "My Pastes" column too narrow

### ISSUE THREAD

**Issue by paroxy777** [jordansamuel/PASTE#187]
Using PASTE fullscreen on a 1920x1080 monitor. The content in the "My Pastes" column on the right-hand side is only 240px wide.  To make things worse, the filenames are truncated after approx 120px being making them only 12 characters longer before the [...].  

Meanwhile, the main paste box on the left has an excessive amount of empty unused horizontal whitespace.

Could there be an option to changed the split, or set a min size for the right column? Maybe have filenames wrap instead of truncate?

I tried adjusting the col-lg-2 and col-lg-10 in the CSS but it didn't matter much because the filenames still truncated after 12 characters.

**Comment by jordansamuel** [comment]
Fiddle with the values in
It is set to truncate a word longer than 6, and no more than 15 characters. Perhaps a value should be added to the config to easily change it, but it was set this way to cater for the lowest screen sizes.

`$title = truncate($title, 6, 15);
`
located in theme/*/sidebar.php

Also, to change the sidebar size
`    <div class="col-md-3 col-lg-2">
`
