### ISSUE TITLE
Support for php8.x

### ISSUE THREAD

**Issue by designstorming** [jordansamuel/PASTE#188]
When installing the app, I get these errors:

`Fatal error: Cannot redeclare str_contains() in {PATH_TO_SERVER}\paste\includes\functions.php on line 16`

When I rename the function, I get these:

```
Deprecated: Required parameter $username follows optional parameter $count in {PATH_TO_SERVER}\paste\includes\functions.php on line 57

Fatal error: Uncaught TypeError: mysqli_fetch_array(): Argument #1 ($result) must be of type mysqli_result, bool given in {PATH_TO_SERVER}\paste\admin\dashboard.php:59
Stack trace: #0 {PATH_TO_SERVER}\paste\admin\dashboard.php(59): mysqli_fetch_array(false) #1 {main} thrown in {PATH_TO_SERVER}\paste\admin\dashboard.php on line 59
```

Also there is a deprecation of `get_magic_quotes_gpc()`.

I did not go deeper in the analysis...

**Comment by thinkverse** [comment]
The latest version of PASTE hasn't been uploaded to Sourceforge. I would recommend grabbing the latest development version directly from GitHub.

```bash
git clone git@github.com:jordansamuel/PASTE.git
```
