### ISSUE TITLE
Where change language on archive page?

### ISSUE THREAD

**Issue by kamis086** [jordansamuel/PASTE#204]
![Zrzut ekranu 2023-04-01 122844](https://user-images.githubusercontent.com/62260910/229280974-91c31281-a4c0-4b5d-9167-90dfbdb94d71.png)

Where change language on archive page?

**Comment by jordansamuel** [comment]
This page is quite universal, displaying Paste title, date and type of paste. There are no plans to include a translator for paste titles.
