### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by shitter** [jordansamuel/PASTE#22]
I downloaded the latest version of your Paste and when I go to the main paste website
http://wotm8.net/paste/
and go to RECENT PASTES and click a Test paste I made it goes http://wotm8.net/paste/2 and it doesn't exist. When I go to admin panel (http://www.wotm8.net/paste/admin/pastes.php) and click view it goes to http://www.wotm8.net/paste/paste.php?id=2. Im looking for a fix

**Comment by shitter** [comment]
lol even when I register I cant go to my profile, settings or anything

**Comment by jordansamuel** [comment]
You'll need to disable mod_rewrite in .htaccess if you're not using Apache.
