### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ChikoritaA** [jordansamuel/PASTE#23]
I have a doubt used the 1.9 and wanted to try out your new project but at the time of registering (install.php) it gives me an error in line 18 problems with "password_hash" could help me. Thanks for everything.

**Comment by jordansamuel** [comment]
Hi. Please make sure you have the requirements installed. see the readme on
http://github.com/jordansamuel/paste

**Comment by ChikoritaA** [comment]
Oh thank you, I saw my mistake
One more thing, the permalink how can I make the links random.
Example
My eighth paste other than http: domain.ico / 8
This has a non-followable address.
Http: domain.ico / 73828

Something like that, just ask if you can.

**Comment by jordansamuel** [comment]
Hello. Please fetch the latest install.php and place it in /install/install.php
