### ISSUE TITLE
Reset/change admin password

### ISSUE THREAD

**Issue by Malchemy** [jordansamuel/PASTE#35]
I somehow could not remember my admin password, and my attempt to search for an answer didn't help. Is there a way I can change the admin password in mysql, like md5('newpass')? Or any other way?

**Comment by Pross** [comment]
Yea, Paste uses password_hash with default options, so put your desired password into this generator and copy the hash into row 1 of the admin table in mysql 

http://www.passwordtool.hu/php5-password-hash-generator

**Comment by Malchemy** [comment]
Ah, thanks.
