### ISSUE TITLE
paste hashes

### ISSUE THREAD

**Issue by sflcnetwork** [jordansamuel/PASTE#36]
Is there any way to change the option from paste id ++ version to hashes instead

**Comment by davidacampos** [comment]
I was looking for the same sort of configuration, but ended up changing the source code, which was simple enough:

DB changes ->
`
ALTER TABLE `paste`.`pastes` 
CHANGE COLUMN `id` `id` VARCHAR(36) NOT NULL ;
`

index.php (line ~365) ->
`
$query = "INSERT INTO pastes (id, title,content,visible,code,expiry,password,encrypt,member,date,ip,now_time,views,s_date) VALUES 
            (uuid(), '$p_title','$p_content','$p_visible','$p_code','$expires','$p_password','$p_encrypt','$p_member','$p_date','$ip','$now_time','0','$date')";
`

**Comment by tsykes** [comment]
This is a few years old but if you come across it and try it, you'll need one more change to paste.php ~ line 43. Comment this out. Maybe change it to parse out spaces or something so that you can keep the string.  

// Prevent SQLInjection
//settype($paste_id, 'integer');
