### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by NykiChannel** [jordansamuel/PASTE#42]
Hello, I'm facing a problem after installation. Gives this error, I insert all the correct data to the database, installed version 5.5
PHP version 5.6
Admin panel is operating normally
Paste 2.1 does not work
Paste 2.0 work

Warning: mysqli_fetch_array() expects parameter 1 to be mysqli_result, boolean given in D:\Site\OpenServer\domains\clear\index.php on line 194
![default](https://cloud.githubusercontent.com/assets/25724849/22863935/9d89f9ec-f159-11e6-8c76-d8db81a1cb1c.PNG)

Russian Version/Русская версия
Здравствуйте, я столкнулся с проблемой после установки. Выдает такую ошибку, ввожу все правильные данные для базы данных, установлена 5.5 версия
PHP версии 5.6
Админ панель работает нормально

**Comment by Vertux** [comment]
Did you read [this](https://github.com/jordansamuel/PASTE#upgrading) ?

**Comment by ToeiRei** [comment]
is this issue still active?
