### ISSUE TITLE
Use of eregi_replace() in mail.php not compatible with PHP 7

### ISSUE THREAD

**Issue by Rocreex** [jordansamuel/PASTE#43]
When registering a new user, eregi_replace() is called when trying to send a confirmation mail in mail.php. This function is deprecated and not part of PHP 7 anymore, which is claimed to be compatible with Paste.

**Comment by ToeiRei** [comment]
You have to use [preg-replace()](http://php.net/manual/en/function.preg-replace.php) instead.
