### ISSUE TITLE
MySQL injection?

### ISSUE THREAD

**Issue by LEGOlord208** [jordansamuel/PASTE#47]
Wait, seriously? Ok, so a friend used this. I tried putting a ' in my name. "Database Error". Wow. Ok, so I looked at the code. NO PREPARED STATMENTS!

wtf. You have a huge SQL injection vulnerability. Seriously, WHAT?

**Comment by jordansamuel** [comment]
I think you'll find there are prepared statements, however queries aren't quoted. We will be implementing PDO so this will be fixed soon.
In the meantime, deez nuts on your chin.

**Comment by attritionorg** [comment]
Does the title change imply that this is an issue?

**Comment by LEGOlord208** [comment]
Umm what?

**Comment by jordansamuel** [comment]
wat. stop carrying on lad.

**Comment by LEGOlord208** [comment]
What? I just changed the name back. It's already marked close.
