### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by ihsansencan** [jordansamuel/PASTE#49]
Hello, many files have sql injection security vulnerability.

**Comment by adammertzenich** [comment]
That is a very big issue.

**Comment by Leykis** [comment]
@ihsansencan @adammertzenich Which files are you seeing the SQL injection in?

**Comment by ihsansencan** [comment]
/paste.php?download&id=
/paste.php?raw&id=
/paste.php?id=
/verify.php?username=
/pages.php?page=
Etc....

**Comment by ToeiRei** [comment]
You could work around that using prepare() for sql statements. Would be the easiest way to prevent havoc

**Comment by LegitSoulja** [comment]
Hey, I recommend https://github.com/LegitSoulja/SlickInject

**Comment by rautamiekka** [comment]
> https://github.com/LegitSoulja/SlickInject

In case someone stumbles here, **be warned SlickInject is strictly MySQLi-only**. For a project which strictly uses MySQLi it's not a problem ...

**Comment by LegitSoulja** [comment]
@rautamiekka I'm making adaptors shortly for it to work for not only MySQLi but PDO aswell.

This project however helps maintain your SQL, prevent injections, and most of all faster and easier to work with. 

Good project to use to start off a base of a php project.

**Comment by LegitSoulja** [comment]
However mysql isn't supported, but can be supported if v1 is modified since it's not using prepare/execute, but rather escaping strings and sending the entire query at once.

**Comment by rautamiekka** [comment]
^ You'd be absolutely mad to use the dangerous, deprecated and deleted old interface.

**Comment by ToeiRei** [comment]
what about pdo?

**Comment by LegitSoulja** [comment]
@rautamiekka I didn't say I recommended it. 

I never felt safe or had confidence of using real escape to protect injections, or to even use mysql. Especially since there's many more options in this generation/era.

**Comment by andreiut** [comment]
Hi, is this SQL Injection bug fixed now? it is safe to use paste project on a new site?
thank you.

**Comment by ToeiRei** [comment]
not yet I fear.

**Comment by andreiut** [comment]
I see, well, i'm new here, i got a cool domain and thought to use this script on it .. as i can see some updates were months ago. do you know if it will be updates&fixes? I also found other bugs.. i reported in other posts.
thank you.

**Comment by ToeiRei** [comment]
I fixed one thing here, but depend on other things. As I'm not the maintainer I'm not going to fix it all on my own as a complete rewrite would be much more efficient

**Comment by rautamiekka** [comment]
^ I'll have to agree on complete (or at least largely completely) rewrite, taking a look at the code.

**Comment by andreiut** [comment]
Oh, i see.. well, don't know if i'm allowed to ask, but is there any other paste script that is updated and secure? thank you :)

**Comment by LegitSoulja** [comment]
@ToeiRei I'd be interested in re-rewriting. I was going to criticize this project, but decided not to, but it's really bad.

If I start this project however, I won't further maintain it afterwards. So, if anyone is interested to do that, be my guest. 

I'll start working on this tomorrow. I think it'll be a fun little project.

**Comment by ToeiRei** [comment]
@LegitSoulja I'd just lift this on PDO and use mysql::prepare and you're pretty much done about the injections.

But looking at the code, it's completely outdated and definitively could need some love and maybe a framework underneath as there are more problems under the hood.

**Comment by andreiut** [comment]
Nice, why don't you guys re-build the script and maintain it ? you could make a better version and put it for sale on codecanyon or somewhere if you plan to offer support and updates..

**Comment by ToeiRei** [comment]
@andreiut short answer: open source spirit

**Comment by LegitSoulja** [comment]
@ToeiRei yes, I do mean an entire new framework/design. 

Nowadays, MVC is a huge thing, so that'll be ported and also thinking about using AngularJS along to aid the UI.

**Comment by Bergiu** [comment]
Is it fixed now?

**Comment by jordansamuel** [comment]
It didn't exist.
