### ISSUE TITLE
Account Registration Spam

### ISSUE THREAD

**Issue by DashieSystems** [jordansamuel/PASTE#61]
Hello! This could already be a feature and I've glazed over it several times, but I've been having issues with an asshat who creates a few spam accounts everyday on my paste site using burner unverified emails. Now, I don't mind clicking the "delete unverified" button, but I wanna solve the root problem (more or less).

Is there something like reCAPTCHA already set up for use during registration to cut down on spam? Thanks!

**Comment by jordansamuel** [comment]
very old issue, new version has server side captcha, recaptcha and options to set pastebin private, so closing.
