### ISSUE TITLE
v2.1 fresh install "Incorrect User/Password" 

### ISSUE THREAD

**Issue by jaygatto** [jordansamuel/PASTE#62]
On local, and remote server installations, post install login as admin returns "Incorrect User/Password".
(v2 installs locally without issue, but fails on remote server)
New, standard user registration works.

**Comment by jaygatto** [comment]
EDIT, UPDATE! 
Admin was logged in already. Suggestion: a link to dashboard, and demarcation on each login.
Regards, Jay

**Comment by RHQ-Rusty** [comment]
> EDIT, UPDATE!
> Admin was logged in already. Suggestion: a link to dashboard, and demarcation on each login.
> Also, disallowing registrations, except via admin/dashboard would be a nice feature.
> Regards, Jay

@jaygatto - I know this is _extremely_ late, but how did you manage to log the Admin account out so you could re-login?
