### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by skapytek** [jordansamuel/PASTE#84]
Hello,
when im trying to save my paste (about 3mb) i get this error message:
Request Entity Too Large
php memory limit is 512mb, upload limit is 128mb, config upload limit for "PASTE" is 50MB.
Any ideas how to fix this error?

regards

**Comment by jordansamuel** [comment]
Your webserver is limiting request sizes.
For Nginx see the value of client_max_body_size in nginx.conf
For Apache see the value of LimitRequestBody in httpd.conf or define it in .htaccess eg LimitRequestBody 104857600 (which is larger than 100MB)
