### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by SandeepanSengupta** [jordansamuel/PASTE#85]
I've installed PASTE via sofaculous
Please provide a how to guide for the followings.

1) Verification mail feature is not working. Please guide how to set up this feature (smtp and all)
2) Chapcha is not working either
3) How to reset/edit paste id
4) How to add custom char to paste id instead of number

Note: I'm new to this and apologize for my limited knowledge, may be the question I'm asking is trivial but still a guidance will be appriciated

**Comment by jordansamuel** [comment]
Have you fixed your issue?
