### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by Bergiu** [jordansamuel/PASTE#87]
This project currently has no license. That makes it proprietary software by default.

**Comment by ChanoAndersen** [comment]
If you look at the top of index.php you will see that it is GPL software.

**Comment by ChanoAndersen** [comment]
The entire GPL is in the docs folder.

**Comment by Bergiu** [comment]
Oh great, I haven't seen it.

And there are some placeholders on lines 634, 635 and 655 in the GPL.txt that should be filled out.
