### ISSUE TITLE
It is not possible to register

### ISSUE THREAD

**Issue by geckoseo** [jordansamuel/PASTE#88]
The registration process doesn't work. It would be nice to be able to register.. the pastebin is much nicer than most others, but we have no way of editing our pasties after they are submitted.

**Comment by jordansamuel** [comment]
Registration works well. You need to properly setup email verification, or
disable it.

**Comment by geckoseo** [comment]
It doesn't work. How do you mean set up registration?

Maybe I have contacted the wrong person?

I'm referring to this:

https://pasteon.site/

If that is not yours then maybe it's a fork, but there is no way to contact the site owner if it's not yours..

**Comment by jordansamuel** [comment]
That's not ours. We provide the software only. The site owner hasn't set up
user registration properly. Email verification requires a working mail
server or SMTP host.

**Comment by geckoseo** [comment]
Ahh, thanks for confirming, I will close this issue. The owner has made themselves unavailable for contact, but in this case I will fork it and set up my own pastebin because the software is amazing.

Thanks for making it open source, always appreciated

**Comment by jordansamuel** [comment]
You can also use the public one at http://pastethis.in

**Comment by geckoseo** [comment]
Even better, top man, thanks very much
